### ISSUE TITLE
ModuleNotFoundError: No module named 'feature_extractor'

### ISSUE THREAD

**Issue by Xt117** [showlab/UniVTG#1]
Hi, thanks for your share.
I ran your project but got the error "ModuleNotFoundError: No module named 'feature_extractor'". Would you please tell me how to get this module?

**Comment by QinghongLin** [comment]
Hi, thanks for your interest and question, this is due to the wrong sub-dir name, I have corrected it.

**Comment by QinghongLin** [comment]
@Xt117 

I have updated the requirements as well as related codes, can you re-try it and let me know?

Thanks!
