### ISSUE TITLE
wating for your code update

### ISSUE THREAD

**Issue by Asimok** [showlab/UniVTG#17]
RuntimeError: Given normalized_shape=[2818], expected input with shape [*, 2818], but got input of size[1, 157, 514]

**Comment by QinghongLin** [comment]
Hi, would you may provide more details for the context? it looks like you load the checkpoints of slowfast+clip in our gradio.py, the solution is replace the slowfast+clip -> clip checkpoints.

**Comment by Asimok** [comment]
I want to use slowfast+clip checkpoints, but the video feature extractor is not compatible.

**Comment by QinghongLin** [comment]
hi, yes, so far the slowfast+clip is not integrated yet since i am quite busy in recent, can you first use the clip checkpoint instead? which will be efficient.

**Comment by Asimok** [comment]
thanks for your work!

**Comment by lcc157** [comment]
@QinghongLin Hi, the slowfast+clip is  integrated yet ?
