### ISSUE TITLE
hdf5 file does not exists

### ISSUE THREAD

**Issue by zhanzhuxi** [showlab/UniVTG#18]
It is a great work!
When I ran this project, I encountered a problem. 
![image](https://github.com/showlab/UniVTG/assets/49984262/9d2bd5da-25ed-43ce-a6bf-e881faf1a8c5)
This problem happened when I tried to run the "qvhl_pretrain.sh" script. The error in the Traceback indicates that the hdf5 file did not exist, meanwhile, it does not exist in the downloaded dataset.

**Comment by JiajunHe1025** [comment]
Have you solved it? I also encountered this problem.

**Comment by zhanzhuxi** [comment]
I resolved this issue by modifying the "use_cache" parameter with 0 in the "qvhl_pretrain.sh" script. Then the code ran correctly. However, I do not know what this parameter represents. Can you answer whether it is valid with this modification and what this parameter means?

**Comment by wenjiajia123** [comment]
> I resolved this issue by modifying the "use_cache" parameter with 0 in the "qvhl_pretrain.sh" script. Then the code ran correctly. However, I do not know what this parameter represents. Can you answer whether it is valid with this modification and what this parameter means?

Hi, does the results get much worser than the given numbers in paper when "use_cazhe" is set to 0 ?🙂

**Comment by zhanzhuxi** [comment]
> > I resolved this issue by modifying the "use_cache" parameter with 0 in the "qvhl_pretrain.sh" script. Then the code ran correctly. However, I do not know what this parameter represents. Can you answer whether it is valid with this modification and what this parameter means?
> 
> Hi, does the results get much worser than the given numbers in paper when "use_cazhe" is set to 0 ?🙂

I have not gotten test results due to some other problems, but results at the inference stage seem normal.

**Comment by QinghongLin** [comment]
> I resolved this issue by modifying the "use_cache" parameter with 0 in the "qvhl_pretrain.sh" script. Then the code ran correctly. However, I do not know what this parameter represents. Can you answer whether it is valid with this modification and what this parameter means?

hi, sorry for late reply. can you list which parameters want me to express? thanks.

**Comment by zhanzhuxi** [comment]
> > I resolved this issue by modifying the "use_cache" parameter with 0 in the "qvhl_pretrain.sh" script. Then the code ran correctly. However, I do not know what this parameter represents. Can you answer whether it is valid with this modification and what this parameter means?
> 
> hi, sorry for late reply. can you list which parameters want me to express? thanks.

The parameter of "use-cache" is set as 1 in the original "qvhl_pretrain.sh" script, but I encountered the problem as shown in the picture of this issue. Then I modified this parameter as 0, and the bug was resolved. However, I did not know what the parameter "use_cache" means and whether modifying this parameter as 0 is valid. Meanwhile, whether this modification can affect the performance of the model.

**Comment by QinghongLin** [comment]
@zhanzhuxi Hi, the `use_cache ` is try to load all train / val features in the cache so that we can avoid frequently io (load features). which should not affect the performance, since the features is pre-extracted and will not change.

**Comment by zhanzhuxi** [comment]
> @zhanzhuxi Hi, the `use_cache ` is try to load all train / val features in the cache so that we can avoid frequently io (load features). which should not affect the performance, since the features is pre-extracted and will not change.

Thank you for your answer!
