### ISSUE TITLE
Dataset feature files

### ISSUE THREAD

**Issue by wsong1106** [showlab/UniVTG#20]
Hi authors -  Thanks for this great work. I fine-tuned the moment retrieval model on my own dataset and would love to do the evaluation on some of the datasets included in your work. I am wondering if you plan to share the CLIP video and text feature files of any or all of QVHighlights, Charades-STA, TACoS, YoutubeHL, TVSum datasets. Thanks.

**Comment by QinghongLin** [comment]
thanks for your interest. i have uploaded all the clip (vid+text) features you mentioned in here: https://github.com/showlab/UniVTG/blob/main/install.md

please take a look.
and you can easily use the feature extractor as in our demo to generate any new features across new datasets.

**Comment by wsong1106** [comment]
Thanks a lot Kevin for your prompt response!
