### ISSUE TITLE
Code for CLIP_teacher

### ISSUE THREAD

**Issue by wenjiajia123** [showlab/UniVTG#22]
Hi, I could not find the code implementation of CLIP teacher, did you upload this part?😊

**Comment by QinghongLin** [comment]
no yeap, but you remind you. i will upload these part this weekend. thanks.

**Comment by wenjiajia123** [comment]
Hi, it seems code files haven't been uploaded？🙂

**Comment by QinghongLin** [comment]
@wenjiajia123 Hi jiajia, Sorry for delay, I just back from travel. 
I will try to update them in recent days, if not, please sent me email for reminds. thanks!

**Comment by QinghongLin** [comment]
@wenjiajia123 Dear jiajia, I have uploaded the code under `teacher/`, please take a look. thanks for your remind.

**Comment by wenjiajia123** [comment]
thank u!😊
