### ISSUE TITLE
The Hugging Space Demo is broken?

### ISSUE THREAD

**Issue by avinabsaha** [showlab/UniVTG#25]
The Hugging Space Demo does not seem to work. I tried with example youtube video running but does not work it seems.

**Comment by QinghongLin** [comment]
Hi @avinabsaha , unfortunately yes, since the huggingface space demo is chargeable. I can't keep it running due to limited badget, so I suggest you set up our gradient demo locally. Thanks.

**Comment by avinabsaha** [comment]
Okay, thanks! I got it running locally.
