### ISSUE TITLE
Implementation on Qvhighlights

### ISSUE THREAD

**Issue by wenjiajia123** [showlab/UniVTG#27]
Hi, I wonder if the results of qvhighlights is got by running train_mr.py? Cause I face same data format problem when it comes to eval.py. tahnk u!😊

**Comment by QinghongLin** [comment]
You can use my model checkpoints with their config for inference, and you should able to reproduce the numbers.
If you want to re-train it. Please load the pretrained weight and then set the parameter settings based on the config. and you can monitor the training logs, find the one with best val scores.
