### ISSUE TITLE
Question about raw videos

### ISSUE THREAD

**Issue by yeliudev** [showlab/UniVTG#31]
Hi @QinghongLin! May I ask that where I can find the raw videos for TACoS and QVFS datasets? It seems that the original authors did not release them. Thank you!

**Comment by QinghongLin** [comment]
Hi @yeliudev , 
For QFVS videos, please visit this instruction: https://github.com/facebookresearch/EgoVLPv2/tree/main/QFVS
For TACoS videos, please visit here: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/human-activity-recognition/mpii-cooking-2-dataset
:)

**Comment by yeliudev** [comment]
Got it. Thank you so much!
