### ISSUE TITLE
What is the version of slowfast(R50)?

### ISSUE THREAD

**Issue by hellojet** [showlab/UniVTG#33]
I tried to extract video features through slowfast 8x8 R50 on the tvsum data set. There are some differences from the features downloaded in the feature file you gave.

given: XzYM3PfTM4w.npz
![image](https://github.com/showlab/UniVTG/assets/15199238/dd460b28-b7e2-400f-9b59-847a5ef8a08c)

extract by slowfast 8x8 R50
![image](https://github.com/showlab/UniVTG/assets/15199238/b3f67db7-6941-4bd7-a41e-7ad1a959752d)

This ended up not working well when I went to test

**Comment by hellojet** [comment]
I am using this version now:

![image](https://github.com/showlab/UniVTG/assets/15199238/f49344d7-20d3-4163-ba57-291b54b4b543)

**Comment by hellojet** [comment]
I know the reason. I accidentally switched the positions of clip and slowfast during concat, which resulted in poor results.

**Comment by QinghongLin** [comment]
Hi @hellojet , have you found the reason? can you please use this codebase for feature extraction. https://github.com/linjieli222/HERO_Video_Feature_Extractor for easy reproduction.
