### ISSUE TITLE
Reproduce of VSLNet on TACoS.

### ISSUE THREAD

**Issue by EricLina** [showlab/UniVTG#34]
Thank you for your excellent work!
In the article, Table 3 mentions the performance of VSLNet on TACoS. Because I noticed that reproducing VSLNet is actually difficult, could you provide the code and checkpoint you used for your VSLNet experiment?

I am appreciate it if you could solve my questions.🥰

**Comment by QinghongLin** [comment]
@EricLina  Hi, Thanks for your interest!

I reproduce the VSLNet based on their pytorch implementation, I think it is not difficult, you just need to re-imple the dataloader.

I attached the Gdrive of the VSLNet codebase I modified.
https://drive.google.com/drive/folders/1dQGjQQ9hFK6rFJfhcGnyGBBTqj3lre-F?usp=sharing

**Comment by EricLina** [comment]
Thanks!🥰
