### ISSUE TITLE
Memory and Time for pretraining

### ISSUE THREAD

**Issue by wjun0830** [showlab/UniVTG#4]
Hello Kevin!

Can you provide how much memory space and time is spent for doing PT?

Thanks

**Comment by QinghongLin** [comment]
Hi @wjun0830 ,

For pretraining, we run on 8GPUs, with less than 24 GB when bsz =32;
10 epoch typically requires 3-4 days;
You can flexible decrease the bsz or transformer project dimension for less memory usage and higher efficiency

**Comment by wjun0830** [comment]
Thank you!
