### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/results/omni/opt.json'

### ISSUE THREAD

**Issue by Xt117** [showlab/UniVTG#6]
Hi, thanks for your update.
I re-tried the project by running the file 'main_gradio.py' for inference, but got the error "FileNotFoundError: [Errno 2] No such file or directory: '/results/omni/opt.json'". Please help me with this error, thanks a lot.

**Comment by QinghongLin** [comment]
Hi! please try to download the opt.json as well in the google drive here https://drive.google.com/drive/folders/1l6RyjGuqkzfZryCC6xwTZsvjWaIMVxIO and put under the `/results/omni` 

<img width="365" alt="image" src="https://github.com/showlab/UniVTG/assets/103281027/8eaf8bfc-2dc2-4a21-bcd0-911424cb6593">

**Comment by Xt117** [comment]
Oh thanks, I only download the model.

**Comment by QinghongLin** [comment]
okay, i will close this question, you can open an issue if you suffer new problem
