### ISSUE TITLE
About the UniVTG License

### ISSUE THREAD

**Issue by koshian2** [showlab/UniVTG#8]
Thanks for the excellent research!
Please let me know the license of this repository.

**Comment by QinghongLin** [comment]
Hi @koshian2 , thanks for your interesting!

I will check and update the license later,
can you kindly tell me which purpose do you want to use?

thanks!

**Comment by koshian2** [comment]
Hi, @QinghongLin ! Thanks for the reply.
I need to know if it can be used for commercial purposes.
If possible, I would be happy with a license like MIT or Apache 2.0

Thanks.

**Comment by QinghongLin** [comment]
@koshian2 Hi, I have updated the license to MIT.
You can use it for commercial purposes, and I am happy it can be used to power more practice scenarios.
but please indicate our original GitHub repo and our paper if applicable.

**Comment by koshian2** [comment]
@QinghongLin 
Amazing!!! Thank you so much.
I would be happy to cite you. I'll be sure to feature your wonderful UniVTG on [my blog](https://blog.shikoan.com/) in the future!
