### ISSUE TITLE
Discrepancy between the video length and the supposed highlight timestamp.

### ISSUE THREAD

**Issue by johind** [showlab/UniVTG#9]
Hi, 

first of all, thanks for releasing the code and model!

While testing the model on huggingface, I noticed a discrepancy between the video length and the supposed highlight timestamp.

The highlight should appear at 54s, but the video is only 30s long.

Do you have any idea why this might happen? (See image below)

Thanks!

![grafik](https://github.com/showlab/UniVTG/assets/10245695/653f9073-9cad-4776-aaa9-43198d34e58e)

**Comment by QinghongLin** [comment]
one possible reason is that the video feature is not match with your current video.
you should first click step2: extract video feature (then it will appear Finish extracting video features. + Please Enter the text query.) and then enter your text query. 

![image](https://github.com/showlab/UniVTG/assets/103281027/cd9c2dc0-101c-4bc8-b446-5a32761d677c)

**Comment by johind** [comment]
Oh yeah, my bad! I somehow thought Step 2 Text was just a Heading and not a Button. Thanks for the help!
